language: objective-c
osx_image: xcode7
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=8.3,name=iPhone 5S" SCHEME="PrephirencesiOS" SDK=iphonesimulator9.0 TEST="test"
    - DESTINATION="OS=8.4,name=iPhone 6" SCHEME="PrephirencesiOS" SDK=iphonesimulator9.0 TEST="test"
    - DESTINATION="OS=9.0,name=iPhone 6" SCHEME="PrephirencesiOS" SDK=iphonesimulator9.0 TEST="test"
    - DESTINATION="arch=x86_64" SCHEME="PrephirencesMacOSX" SDK=macosx10.11 TEST=""
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project Prephirences.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Debug ONLY_ACTIVE_ARCH=NO $TEST | xcpretty -c
  - xcodebuild -project Prephirences.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Release ONLY_ACTIVE_ARCH=NO $TEST | xcpretty -c